# Generated by Django 5.2.10 on 2026-01-25 15:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('blood_group', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=3)),
                ('marital_status', models.CharField(blank=True, choices=[('SINGLE', 'Single'), ('MARRIED', 'Married')], max_length=10)),
                ('email_address', models.EmailField(blank=True, max_length=254)),
                ('residential_address', models.TextField(blank=True)),
                ('permanent_address', models.TextField(blank=True)),
                ('contact_number', models.CharField(blank=True, max_length=15)),
                ('emergency_contact_number', models.CharField(blank=True, max_length=15)),
                ('employee_id', models.CharField(help_text='Official Employee ID', max_length=20, unique=True)),
                ('designation', models.CharField(blank=True, choices=[('ASSOCIATE', 'Associate'), ('SENIOR_ASSOCIATE', 'Senior Associate'), ('TEAM_LEADER', 'Team Leader'), ('MANAGER', 'Manager'), ('SENIOR MANAGER', 'Senior Manager'), ('VICE PRESIDENT', 'vice president'), ('PRESIDENT', 'president'), ('CEO', 'CEO'), ('HR', 'HR')], max_length=30)),
                ('department', models.CharField(blank=True, choices=[('IT', 'IT'), ('DEVELOPER', 'Developer'), ('HR', 'HR'), ('MANAGEMENT', 'Management')], max_length=30)),
                ('client', models.CharField(blank=True, max_length=100)),
                ('reporting_role', models.CharField(blank=True, choices=[('ASSOCIATE', 'Associate'), ('SENIOR_ASSOCIATE', 'Senior Associate'), ('TEAM_LEADER', 'Team Leader'), ('MANAGER', 'Manager'), ('SENIOR MANAGER', 'Senior Manager'), ('VICE PRESIDENT', 'vice president'), ('PRESIDENT', 'president'), ('CEO', 'CEO'), ('HR', 'HR')], help_text='Role/designation this employee reports to', max_length=30)),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('ending_date', models.DateField(blank=True, null=True)),
                ('employment_status', models.CharField(choices=[('ACTIVE', 'Active'), ('TERMINATED', 'Terminated'), ('ABSCOND_TERMINATED', 'Absconded-Terminated')], default='ACTIVE', max_length=25)),
                ('is_locked', models.BooleanField(default=False)),
                ('failed_login_attempts', models.PositiveIntegerField(default=0)),
                ('force_password_reset', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reporting_person', models.ForeignKey(blank=True, help_text='Actual employee in the selected reporting role', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportees', to='wrad.employee')),
                ('user', models.OneToOneField(blank=True, help_text='Linked login account', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeLogHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(help_text='Description of the action performed', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='wrad.employee')),
            ],
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('CASUAL', 'Casual Leave'), ('SICK', 'Sick Leave'), ('PERMISSION', 'Permission')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_days', models.PositiveIntegerField()),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('SENT_BACK', 'Sent Back'), ('CANCELLED', 'Cancelled')], default='SUBMITTED', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_leave_approvals', to='wrad.employee')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='wrad.employee')),
            ],
        ),
        migrations.CreateModel(
            name='LeaveApprovalLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('SENT_BACK', 'Sent Back')], max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('action_at', models.DateTimeField(auto_now_add=True)),
                ('action_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wrad.employee')),
                ('leave_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_logs', to='wrad.leaverequest')),
            ],
        ),
    ]
