# Generated by Django 5.2.10 on 2026-01-26 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_employees', to='wrad.employee'),
        ),
        migrations.AddField(
            model_name='employee',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Soft delete flag (Management only)'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='designation',
            field=models.CharField(blank=True, choices=[('ASSOCIATE', 'Associate'), ('SENIOR_ASSOCIATE', 'Senior Associate'), ('TEAM_LEADER', 'Team Leader'), ('MANAGER', 'Manager'), ('SENIOR_MANAGER', 'Senior Manager'), ('VICE_PRESIDENT', 'Vice President'), ('PRESIDENT', 'President'), ('CEO', 'CEO'), ('HR', 'HR')], max_length=30),
        ),
        migrations.AlterField(
            model_name='employee',
            name='reporting_role',
            field=models.CharField(blank=True, choices=[('ASSOCIATE', 'Associate'), ('SENIOR_ASSOCIATE', 'Senior Associate'), ('TEAM_LEADER', 'Team Leader'), ('MANAGER', 'Manager'), ('SENIOR_MANAGER', 'Senior Manager'), ('VICE_PRESIDENT', 'Vice President'), ('PRESIDENT', 'President'), ('CEO', 'CEO'), ('HR', 'HR')], help_text='Role/designation this employee reports to', max_length=30),
        ),
    ]
