# Generated by Django 5.2.10 on 2026-01-26 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrad', '0002_employee_deleted_at_employee_deleted_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(help_text='Type of action (PROFILE_UPDATE, ADMIN_EDIT, SOFT_DELETE, RESTORE)', max_length=100)),
                ('before_data', models.JSONField(help_text='Employee state before change')),
                ('after_data', models.JSONField(help_text='Employee state after change')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, help_text='Employee who performed the action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_snapshots', to='wrad.employee')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='wrad.employee')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
