# Generated by Django 5.2.10 on 2026-02-02 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrad', '0003_employeesnapshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(blank=True, choices=[('IT', 'IT'), ('ADMIN', 'Admin'), ('DEVELOPER', 'Developer'), ('HR', 'HR'), ('MANAGEMENT', 'Management')], max_length=30),
        ),
    ]
