# Generated by Django 5.2.10 on 2026-02-09 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrad', '0005_task_taskupdatelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(),
        ),
    ]
